### ISSUE TITLE
Missing games.txt

### ISSUE THREAD

**Issue by hubertye** [hunter-college-ossd-fall-2019/cats-workflow#7]
Missing a text file containing the favorite games of each member.

**Comment by hubertye** [comment]
Can I have your favorite games?

**Comment by waterpolymer** [comment]
Zelda: Ocarina of Time

**Comment by khinshankhan** [comment]
Mine is Megaman, but if you don't mind, I'll tackle this issue. @HubertYe could you respond with yours?

**Comment by hubertye** [comment]
Okay, Azur Lane.
